cursor            #e0b6ff
cursor_text_color #490079

foreground            #eadfed
background            #231a29
selection_foreground  #3e2642
selection_background  #ddbcdf
url_color             #ddbcdf

color0                #241b2b
color1                #ffb4ab
color2                #efb5df
color3                #ddbcdf
color4                #e0b6ff
color5                #efb5df
color6                #ddbcdf
color7                #eadfed

color8                #4c444f
color9                #ffcbc5
color10               #704366
color11               #634967
color12               #7b00c7
color13               #573e5b
color14               #64385b
color15               #cec3d1

mark1_foreground #2e004e
mark1_background #f2daff
mark2_foreground #29132e
mark2_background #fbd7fc
mark3_foreground #5b1652
mark3_background #ffd7f2

active_tab_foreground #490079
active_tab_background #e0b6ff
inactive_tab_foreground #ffffff
inactive_tab_background #7b00c7

active_border_color #e0b6ff
inactive_border_color #490079

color255              #7b00c7
color254              #e0b6ff
color253              #634967
color252              #ddbcdf
color251              #704366
color250              #efb5df
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #490079
color234              #ffffff
color235              #3e2642
color236              #ffffff
color237              #482042
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #e0b6ff
color244              #ffb4ab
color245              #574f5b

