cursor            #ddb9f7
cursor_text_color #3e2256

foreground            #e8e0e8
background            #211c24
selection_foreground  #352b3d
selection_background  #d1c1d9
url_color             #d1c1d9

color0                #221d25
color1                #ffb4ab
color2                #f4b7bb
color3                #d1c1d9
color4                #ddb9f7
color5                #f4b7bb
color6                #d1c1d9
color7                #e8e0e8

color8                #4b454d
color9                #ffcbc5
color10               #724549
color11               #5a4d61
color12               #63457b
color13               #4e4256
color14               #663a3f
color15               #cdc3ce

mark1_foreground #2a0c41
mark1_background #f2daff
mark2_foreground #211829
mark2_background #eeddf6
mark3_foreground #591c25
mark3_background #ffdadb

active_tab_foreground #3e2256
active_tab_background #ddb9f7
inactive_tab_foreground #ffffff
inactive_tab_background #63457b

active_border_color #ddb9f7
inactive_border_color #3e2256

color255              #63457b
color254              #ddb9f7
color253              #5a4d61
color252              #d1c1d9
color251              #724549
color250              #f4b7bb
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #3e2256
color234              #ffffff
color235              #352b3d
color236              #ffffff
color237              #4a2327
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #ddb9f7
color244              #ffb4ab
color245              #565059

