cursor            #c4c0ff
cursor_text_color #2b285e

foreground            #e5e1e9
background            #1d1d25
selection_foreground  #2e2d40
selection_background  #c7c4dc
url_color             #c7c4dc

color0                #1e1e26
color1                #ffb4ab
color2                #eab9d1
color3                #c7c4dc
color4                #c4c0ff
color5                #eab9d1
color6                #c7c4dc
color7                #e5e1e9

color8                #47464f
color9                #ffcbc5
color10               #6c465b
color11               #515064
color12               #4e4b84
color13               #464559
color14               #603b4f
color15               #c8c5d0

mark1_foreground #17134a
mark1_background #e3dfff
mark2_foreground #1a1a2c
mark2_background #e3e0f9
mark3_foreground #541f3f
mark3_background #ffd8ea

active_tab_foreground #2b285e
active_tab_background #c4c0ff
inactive_tab_foreground #ffffff
inactive_tab_background #4e4b84

active_border_color #c4c0ff
inactive_border_color #2b285e

color255              #4e4b84
color254              #c4c0ff
color253              #515064
color252              #c7c4dc
color251              #6c465b
color250              #eab9d1
color249              #a7060f
color248              #ffb4ab

color232              #ffffff
color233              #2b285e
color234              #ffffff
color235              #2e2d40
color236              #ffffff
color237              #452437
color238              #ffffff
color239              #660004
color240              #ffffff

color243              #c4c0ff
color244              #ffb4ab
color245              #52515a

