$background = 040505
$onBackground = e1e3e3
$surface = 040505
$surfaceDim = 040505
$surfaceBright = 101010
$surfaceContainerLowest = 020303
$surfaceContainerLow = 060808
$surfaceContainer = 080909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e1e3e3
$surfaceVariant = 121414
$onSurfaceVariant = bfc8ca
$outline = 899294
$outlineVariant = 40484a
$inverseSurface = e1e3e3
$inverseOnSurface = 2e3131
$shadow = 000000
$scrim = 000000
$surfaceTint = 132b2f
$primary = 99d4dd
$primaryDim = b4eff9
$onPrimary = 00363c
$primaryContainer = 7eb8c1
$onPrimaryContainer = 004951
$inversePrimary = 2a676f
$primaryFixed = b1ecf6
$primaryFixedDim = 96d0d9
$onPrimaryFixed = 001f23
$onPrimaryFixedVariant = 064e56
$secondary = b4cbce
$secondaryDim = d0e7ea
$onSecondary = 1f3437
$secondaryContainer = 354a4d
$onSecondaryContainer = a3b9bd
$secondaryFixed = d0e7ea
$secondaryFixedDim = b4cbce
$onSecondaryFixed = 091f22
$onSecondaryFixedVariant = 354a4d
$tertiary = d8c1f2
$tertiaryDim = e0c8f9
$onTertiary = 39284f
$tertiaryContainer = bca6d5
$onTertiaryContainer = 4c3a62
$tertiaryFixed = eedcff
$tertiaryFixedDim = d4bdee
$onTertiaryFixed = 241339
$onTertiaryFixedVariant = 513f67
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 468088
$secondaryPaletteKeyColor = 657b7e
$tertiaryPaletteKeyColor = bca6d5
$neutralPaletteKeyColor = 757778
$neutralVariantPaletteKeyColor = 70797a
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 468088
$secondary_paletteKeyColor = 657b7e
$tertiary_paletteKeyColor = bca6d5
$neutral_paletteKeyColor = 757778
$neutral_variant_paletteKeyColor = 70797a
$term0 = 080808
$term1 = 8383ff
$term2 = 45e1d4
$term3 = 75fcdd
$term4 = 76b4bc
$term5 = 7aaee9
$term6 = 80d8d6
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 18f7e8
$term11 = c9fff3
$term12 = a3c8c9
$term13 = a2c0f7
$term14 = 87ece9
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 6bccf4
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d1faf1
$green = 8af1ef
$teal = 9eedf3
$sky = 94e8f5
$sapphire = 73d5e8
$blue = 5ecae7
$lavender = 8bd7f2
$klink = 0094ac
$klinkSelection = 0094ac
$kvisited = 008bb5
$kvisitedSelection = 008bb5
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bcbd
$kpositiveSelection = 00bcbe
$text = e1e3e3
$subtext1 = bfc8ca
$subtext0 = 899294
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0d0d0d
$surface0 = 060707
$base = 000101
$mantle = 000101
$crust = 000101
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
