input {
    kb_layout = us
    kb_variant = qwerty-fr
    follow_mouse = 1
    repeat_delay = 250
    repeat_rate = 35
    
    touchpad {
        natural_scroll = true
        tap-to-click = true
        scroll_factor = 0.5
    }
}
bind = Super, TAB, exec, qs ipc -c overview call overview toggle
bind = Super, P, exec,
exec-once = qs -c overview
# bindin = Super, catchall, global, caelestia:launcherInterrupt  ← désactiver
# bind = Super, Space, exec, qs -c caelestia ipc call drawers toggle launcher
exec = hyprshade auto
monitor=DP-3,1920x1080@60,0x0,1
animations {
    enabled = true

    bezier = instant, 1, 1, 1, 1

    animation = windowsIn, 1, 0.001, instant, popin 95%
    animation = windowsOut, 1, 0.001, instant, popin 95%

    animation = windowsMove, 1, 0.001, instant
    animation = workspaces, 1, 0.001, instant
    animation = fade, 1, 0.001, instant
    animation = layers, 1, 0.001, instant
}
monitor=HDMI-A-3,1920x1080@60,1920x0,1
decoration{
  rounding = 8
    shadow{
        enabled = true
        range = 5
        sharp = false
      }
  }


# Philips (HDMI-A-3)
workspace = 1, monitor:HDMI-A-3
workspace = 2, monitor:HDMI-A-3
workspace = 3, monitor:HDMI-A-3
workspace = 4, monitor:HDMI-A-3
workspace = 5, monitor:HDMI-A-3

# Samsung (DP-3)
workspace = 6, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 10, monitor:DP-3


bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
# Déplacer la fenêtre active vers le workspace suivant/précédent
bind = SUPER SHIFT, mouse_down, movetoworkspace, +1
bind = SUPER SHIFT, mouse_up, movetoworkspace, -1
