color0 #3e484d
color1 #ffb4ab
color2 #74d2f8
color3 #aaccdc
color4 #e8b3ff
color5 #74d2f8
color6 #aaccdc
color7 #dfe3e6
color8 #889298
color9 #ffb4ab
color10 #74d2f8
color11 #aaccdc
color12 #e8b3ff
color13 #74d2f8
color14 #aaccdc
color15 #dfe3e6

cursor                #dfe3e6
cursor_text_color     #101416
background            #101416
foreground            #dfe3e6
selection_foreground  #bec8ce
selection_background  #3e484d
active_border_color   #74d2f8
inactive_border_color #3e484d
url_color             #74d2f8

active_tab_foreground   #003545
active_tab_background   #74d2f8
inactive_tab_foreground #bec8ce
inactive_tab_background #3e484d
cursor_trail_color      #bec8ce
