color0 #121315
color1 #ffb4ab
color2 #b4c7ea
color3 #c0c7d6
color4 #e2badd
color5 #b4c7ea
color6 #c0c7d6
color7 #e4e2e5
color8 #8e9098
color9 #ffb4ab
color10 #b4c7ea
color11 #c0c7d6
color12 #e2badd
color13 #b4c7ea
color14 #c0c7d6
color15 #e4e2e5

cursor                #e4e2e5
cursor_text_color     #121315
background            #121315
foreground            #e4e2e5
selection_foreground  #c4c6ce
selection_background  #44474d
active_border_color   #b4c7ea
inactive_border_color #44474d
url_color             #b4c7ea

active_tab_foreground   #1d314d
active_tab_background   #b4c7ea
inactive_tab_foreground #c4c6ce
inactive_tab_background #44474d
cursor_trail_color      #c4c6ce
