color0 #42474e
color1 #ffb4ab
color2 #a4caf2
color3 #bac8d9
color4 #e1b9ea
color5 #a4caf2
color6 #bac8d9
color7 #e2e2e5
color8 #8c9198
color9 #ffb4ab
color10 #a4caf2
color11 #bac8d9
color12 #e1b9ea
color13 #a4caf2
color14 #bac8d9
color15 #e2e2e5

cursor                #e2e2e5
cursor_text_color     #121316
background            #121316
foreground            #e2e2e5
selection_foreground  #c2c7cf
selection_background  #42474e
active_border_color   #a4caf2
inactive_border_color #42474e
url_color             #a4caf2

active_tab_foreground   #013353
active_tab_background   #a4caf2
inactive_tab_foreground #c2c7cf
inactive_tab_background #42474e
cursor_trail_color      #c2c7cf
