# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131315ff
bordercolor = 0x909098ff
focuscolor = 0xbdc5e7ff
maximizescreencolor = 0xc4c6d4ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe2bbd7ff
globalcolor = 0x3d4661ff
overlaycolor = 0x434652ff
