# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x121318ff
bordercolor = 0x8d909cff
focuscolor = 0xafc6ffff
maximizescreencolor = 0xbac6e9ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xf5aefbff
globalcolor = 0x1b448bff
overlaycolor = 0x3a4663ff
