# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x17111bff
bordercolor = 0x9a8ca0ff
dropcolor = 0xe1b6ff80
splitcolor = 0xffafd7ff
focuscolor = 0xe1b6ffff
maximizescreencolor = 0xe1b6ffff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xffafd7ff
globalcolor = 0x8b0bdcff
overlaycolor = 0x602e88ff
jump_label_decorate_fg_color = 0xebdeeeff
jump_label_decorate_bg_color = 0x2e2733ff
jump_label_decorate_focus_fg_color = 0x4c007cff
jump_label_decorate_focus_bg_color = 0xe1b6ffff
jump_label_decorate_border_color = 0x9a8ca0ff
group_bar_decorate_fg_color = 0xebdeeeff
group_bar_decorate_bg_color = 0x2e2733ff
group_bar_decorate_focus_fg_color = 0x4c007cff
group_bar_decorate_focus_bg_color = 0xe1b6ffff
group_bar_decorate_border_color = 0x9a8ca0ff
