# ~/.config/mango/rule.conf
# Window Rules for Mango

# ─── Floating window with custom size (Activée !) ───
windowrule=isfloating:1,width:950,height:600,title:floating-kitty

# ─── Steam: idle inhibit ───
windowrule=indleinhibit_when_focus:1,appid:steam

# ─── Wallpaper picker: always floating ───
windowrule=isfloating:1,title:Wallpaper Picker
smartgaps=1
no_border_when_single=1
no_radius_when_single=1
