# ~/.config/mango/tag.conf
# Tag configuration
tagrule=id:1,monitor_name:.*,layout_name:dwindle
tagrule=id:2,monitor_name:.*,layout_name:scroller

tagrule=id:1,monitor_name:^DP-1$,layout_name:dwindle

tagrule=id:1,monitor_name:^DP-2$,layout_name:grid
tagrule=id:2,monitor_name:^DP-2$,layout_name:grid
tagrule=id:3,monitor_name:^DP-2$,layout_name:grid
tagrule=id:4,monitor_name:^DP-2$,layout_name:grid
tagrule=id:5,monitor_name:^DP-2$,layout_name:grid
tagrule=id:6,monitor_name:^DP-2$,layout_name:grid
tagrule=id:7,monitor_name:^DP-2$,layout_name:grid
tagrule=id:8,monitor_name:^DP-2$,layout_name:grid
tagrule=id:9,monitor_name:^DP-2$,layout_name:grid
